"""empty message

Revision ID: 730b5d1219cc
Revises: 988ad325cd7a
Create Date: 2024-01-04 22:03:58.325085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730b5d1219cc'
down_revision = '988ad325cd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['sno'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['sno'])
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
